In [2]:
import pandas as pd

df = pd.read_csv("ecommerce_sales_analytics_5000.csv", parse_dates=["order_date"])

In [3]:
# Verify

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[ns]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(3)
memory usage: 468.9+ KB

In [8]:
# map() = label high value orders
df["payment_type"] = df["payment_method"].map({  # this method will apply on payment_method column and create a new column "payment_tyoe"
    "Card": "Digital",
    "Wallet": "Digital",
    "COD": "Cash"
})

# Explanation: each value is mapped individually fast and simple

In [9]:
# verify
df["payment_type"].unique()  # It will show that there are new unique value 'Digital' and 'cash'

array(['Digital', 'Cash'], dtype=object)

In [12]:
df[["payment_method", "payment_type"]].head()

  payment_method payment_type
0         Wallet      Digital
1           Card      Digital
2            COD         Cash
3         Wallet      Digital
4         Wallet      Digital

In [15]:
df.groupby("payment_type").size()

payment_type
Cash       1774
Digital    3226
dtype: int64

In [18]:
# apply Create revenue category

def revenue_category(row):
    if row["revenue"] > 500:
        return "High"
    elif row["revenue"] >= 200:
        return "Mediam"
    else:
        return "Low"

df["revenue_category"] = df.apply(revenue_category, axis=1) # new revenue_category column will be created based on vevenue using the above if else formula


# why apply? Decision depends on multiple columns.

In [20]:
# verify
df["revenue_category"].value_counts() # check categories

revenue_category
High      3252
Mediam    1098
Low        650
Name: count, dtype: int64

In [21]:
df[["revenue", "revenue_category"]].sample(10)
# Revenue > 500 -> High
# Revenue 200 - 500 -> Mediam
# < 200 -> Low

      revenue revenue_category
2020  1820.70             High
3864   183.40              Low
2964  1446.87             High
4528   286.23           Mediam
2929   629.76             High
4085   444.14           Mediam
2918  2081.96             High
1798   359.27           Mediam
2174   287.93           Mediam
4061   196.20              Low

In [22]:
# pipe() - Method Chaining 
def add_profit(data):
    data["profit"] = data["revenue"] * 0.20
    return data

def add_net_revenue(data):
    data["net_revenue"] = data["revenue"] - data["profit"]
    return data

      # series of operations to be performed on dataset

df = (
    df
    .pipe(add_profit)
    .pipe(add_net_revenue)
)

In [24]:
# verify
df[["revenue", "profit", "net_revenue"]].head() # check new column

   revenue   profit  net_revenue
0  1883.20  376.640     1506.560
1   304.10   60.820      243.280
2   644.35  128.870      515.480
3  2569.90  513.980     2055.920
4   468.56   93.712      374.848